spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGIN}

openapi:
  service:
    api-docs: samcenter-backend
    server: http://localhost:8080
    title: Backend
    version: 1.0.0

jwt:
  expiryMinutes: ${JWT_EXPIRY_MINUTES}
  expiryDay: ${JWT_EXPIRY_DAY}
  accessKey: ${JWT_ACCESS_KEY}
  refreshKey: ${JWT_REFRESH_KEY}